version: '3.7'

services:
  python-ai:
    build: ./python_ai
    ports:
      - "5000:5000"
    volumes:
      - python_ai_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  spring-backend:
    build:
      context: ./spring_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - spring_data:/app
    depends_on:
      - python-ai

volumes:
  python_ai_data:
  spring_data: