version: '3.7'

services:
  python-ai:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 -m uvicorn main:app --host 0.0.0.0 --port 5000

volumes:
  data: